##Loading the dataset

In [1]:
from PIL import Image
import cv2
import numpy as np

In [2]:
import zipfile
path = 'Datasets/yalefaces.zip'
zip_object = zipfile.ZipFile(file=path, mode = 'r')
zip_object.extractall('./')
zip_object.close()

##Pre-processing the images

In [3]:
import os
print(os.listdir('yalefaces\\train'))

['subject01.glasses.gif', 'subject01.leftlight.gif', 'subject01.noglasses.gif', 'subject01.normal.gif', 'subject01.rightlight.gif', 'subject01.sad.gif', 'subject01.sleepy.gif', 'subject01.surprised.gif', 'subject01.wink.gif', 'subject02.glasses.gif', 'subject02.happy.gif', 'subject02.noglasses.gif', 'subject02.normal.gif', 'subject02.rightlight.gif', 'subject02.sad.gif', 'subject02.sleepy.gif', 'subject02.surprised.gif', 'subject02.wink.gif', 'subject03.centerlight.gif', 'subject03.happy.gif', 'subject03.noglasses.gif', 'subject03.normal.gif', 'subject03.rightlight.gif', 'subject03.sad.gif', 'subject03.sleepy.gif', 'subject03.surprised.gif', 'subject03.wink.gif', 'subject04.centerlight.gif', 'subject04.glasses.gif', 'subject04.happy.gif', 'subject04.noglasses.gif', 'subject04.normal.gif', 'subject04.rightlight.gif', 'subject04.sad.gif', 'subject04.sleepy.gif', 'subject04.wink.gif', 'subject05.centerlight.gif', 'subject05.glasses.gif', 'subject05.happy.gif', 'subject05.leftlight.gif', '

In [4]:
def get_image_data():
  paths = [os.path.join('yalefaces\\train', f) for f in os.listdir('yalefaces\\train')]
  print(paths)
  faces = []
  ids = []
  for path in paths:
    #print(path)
    image = Image.open(path).convert('L')
    #print(type(image))
    image_np = np.array(image, 'uint8')
    #print(type(image_np))
    id = int(os.path.split(path)[1].split('.')[0].replace('subject', ''))
    #print(id)
    ids.append(id)
    faces.append(image_np)

  return np.array(ids), faces

In [5]:
ids, faces = get_image_data()

['yalefaces\\train\\subject01.glasses.gif', 'yalefaces\\train\\subject01.leftlight.gif', 'yalefaces\\train\\subject01.noglasses.gif', 'yalefaces\\train\\subject01.normal.gif', 'yalefaces\\train\\subject01.rightlight.gif', 'yalefaces\\train\\subject01.sad.gif', 'yalefaces\\train\\subject01.sleepy.gif', 'yalefaces\\train\\subject01.surprised.gif', 'yalefaces\\train\\subject01.wink.gif', 'yalefaces\\train\\subject02.glasses.gif', 'yalefaces\\train\\subject02.happy.gif', 'yalefaces\\train\\subject02.noglasses.gif', 'yalefaces\\train\\subject02.normal.gif', 'yalefaces\\train\\subject02.rightlight.gif', 'yalefaces\\train\\subject02.sad.gif', 'yalefaces\\train\\subject02.sleepy.gif', 'yalefaces\\train\\subject02.surprised.gif', 'yalefaces\\train\\subject02.wink.gif', 'yalefaces\\train\\subject03.centerlight.gif', 'yalefaces\\train\\subject03.happy.gif', 'yalefaces\\train\\subject03.noglasses.gif', 'yalefaces\\train\\subject03.normal.gif', 'yalefaces\\train\\subject03.rightlight.gif', 'yalefac

In [6]:
ids

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  3,  3,  3,  3,  3,  3,  3,  3,  3,  4,  4,  4,  4,  4,  4,  4,
        4,  4,  5,  5,  5,  5,  5,  5,  5,  5,  5,  6,  6,  6,  6,  6,  6,
        6,  6,  6,  7,  7,  7,  7,  7,  7,  7,  7,  7,  8,  8,  8,  8,  8,
        8,  8,  8,  8,  9,  9,  9,  9,  9,  9,  9,  9,  9, 10, 10, 10, 10,
       10, 10, 10, 10, 10, 11, 11, 11, 11, 11, 11, 11, 11, 11, 12, 12, 12,
       12, 12, 12, 12, 12, 12, 13, 13, 13, 13, 13, 13, 13, 13, 13, 14, 14,
       14, 14, 14, 14, 14, 14, 14, 15, 15, 15, 15, 15, 15, 15, 15, 15])

In [7]:
len(ids)

135

In [8]:
len(faces)

135

In [9]:
faces[0], faces[0].shape

(array([[130, 130, 130, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        ...,
        [255, 255, 255, ..., 252, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        [ 68,  68,  68, ...,  68,  68,  68]], dtype=uint8),
 (243, 320))

In [10]:
243 * 320

77760

##Training the LBPH classifier

In [11]:
# threshold: 1.7976931348623157e+308
# radius: 1
# neighbors: 8
# grid_x: 8
# grid_y: 8

lbph_classifier = cv2.face.LBPHFaceRecognizer_create(radius = 4, neighbors=14, grid_x = 9, grid_y = 9)
lbph_classifier.train(faces, ids)
lbph_classifier.write('lbph_classifier.yml')

##Recognizing faces

In [12]:
lbph_face_classifier = cv2.face.LBPHFaceRecognizer_create()
lbph_face_classifier.read('lbph_classifier.yml')

In [13]:
test_image = 'yalefaces/test/subject09.sad.gif'

In [14]:
image = Image.open(test_image).convert('L')
image_np = np.array(image, 'uint8')
image_np

array([[130, 130, 130, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       ...,
       [255, 255, 255, ..., 255, 238, 237],
       [255, 255, 255, ..., 255, 235, 237],
       [ 68,  68,  68, ...,  68,  68,  68]], dtype=uint8)

In [15]:
image_np.shape

(243, 320)

In [16]:
prediction = lbph_face_classifier.predict(image_np)
prediction

(9, 63.38040010596866)

In [17]:
prediction[0]

9

In [18]:
expected_output = int(os.path.split(test_image)[1].split('.')[0].replace('subject', ''))
expected_output

9

In [19]:
cv2.putText(image_np, 'Pred: ' + str(prediction[0]), (10, 30), cv2.FONT_HERSHEY_COMPLEX_SMALL, 1, (0,255,0))
cv2.putText(image_np, 'Exp: ' + str(expected_output), (10, 50), cv2.FONT_HERSHEY_COMPLEX_SMALL, 1, (0,255,0))


#To Display image
if image is not None:
    # Display the image
    cv2.imshow('image', image_np)

    # Wait for a key press and close the window
    cv2.waitKey(0)
    cv2.destroyAllWindows()
else:
    print("Error: Unable to read the image.")